# Generated by Django 3.0.3 on 2020-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='docflowapp.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='counterpart',
            field=models.ManyToManyField(blank=True, to='docflowapp.Counterpart'),
        ),
    ]
